smartcode:
  datasource:
    host: 192.168.232.101
    port: 3306
    database: smart_code
    username: root
    password: *******

  redis:
    host: 192.168.232.101
    port: 6379
    database: 1

  oss:
    access-key-id: ************
    access-key-secret: **********
    bucket-name: ***********
    endpoint: ***********

  sms:
    access-key-id: ***********
    access-key-secret: ************
    endpoint: ***************

