smartcode:
  datasource:
    host: 192.168.232.101
    port: 3306
    database: smart_code
    username: root
    password: Atguigu.123

  redis:
    host: 192.168.232.101
    port: 6379
    database: 1

  oss:
    access-key-id: LTAI5tBzAd9N7xL4LTYcRY76
    access-key-secret: tWLkG7BJovMY8thJ5ncKJlrUCAAEu7
    bucket-name: smart-code
    endpoint: oss-cn-guangzhou.aliyuncs.com

  sms:
    access-key-id: LTAI5tBv3vxGYizMDfxqYyyu
    access-key-secret: rDpmVF229Z7wVowFK9tVHAzGqJS5zB
    endpoint: dysmsapi.aliyuncs.com

